### ISSUE TITLE
Continuously stake and progress

### ISSUE THREAD

**Issue by schemar** [OpenST/JLP#18]
Branded token stake.

Set up and fund separate keys dedicated to the facilitator process.

Stake a random number within a sensible range. Doesn't need to be huge.

Monitoring would be a separate ticket. For now, we can log in once per day and check that it is still successfully staking.

**Comment by benjaminbollen** [comment]
this should be done as a JLP executable, not as a smoke test

**Comment by benjaminbollen** [comment]
specify the cli parameters first

**Comment by abhayks1** [comment]
The implementation of the ticket consumes proofGenerator of Mosaic.js. 
proofGenerator in mosaic.js uses eth_getProof jsonrpc call. ZeroClientProvider uses web3-provider-engine as ProviderEngine which has implemented sendAsync but throws error on calling send.
```
Error: Web3ProviderEngine does not support synchronous requests.
```

The ticket should be closed after fixing https://github.com/openst/mosaic.js/issues/158

**Comment by schemar** [comment]
JLP is considered "✅ done" for now.
