### ISSUE TITLE
TokenRules Direct transfer from TH Sender to receivers

### ISSUE THREAD

**Issue by abhayks1** [OpenST/JLP#34]
- Register sender/receiver(s) as internal actor.
- ephemeralKey performs 1077 signing.
- Command
  	**directTransfer config.json sessionKey sender beneficiaries amounts**	
- Add directTransfer under test framework.

**Comment by schemar** [comment]
No PR assigned to this issue.

**Comment by abhayks1** [comment]
**25/03/2019 Update**
Addressed Banks PR feedback changes and improvements

**Comment by abhayks1** [comment]
PreRequisites smoke tests for the test to work:

- Openst setup smoke test is already run.
   Master copies will be read from chainConfig shared object.

- TokenHolder UserWallet is  created which will act as sender. Sender is registered as internal actor.

- Stake and mint of BT is smoke test is run. 
   This way we will have minted BTs available to a sender.

We already have an integration test ticket:
https://github.com/OpenST/JLP/issues/75

cc: @sarvesh-ost @jasonklein @benjaminbollen
