### ISSUE TITLE
Recovery: InitiateAndExecuteRecovery / abortRecoveryByRecoveryOwner

### ISSUE THREAD

**Issue by abhayks1** [OpenST/JLP#40]
InitiateAndExecuteRecovery
- recovery owner does EIP712 signing	

- Command
	initiateAndExecuteRecovery config.json oldOwner newOwner

abortRecoveryByRecoveryOwner
- recovery owner does EIP712 signing	

- Command
	abortRecoveryByOwner config.json oldOwner newOwner

**Comment by pgev** [comment]
Closing the ticket as "abort recovery" smoke tests is already implemented and for "initiate and execute recovery" new ticket (https://github.com/OpenST/JLP/issues/87) has been created.
