### ISSUE TITLE
BrandedToken Facilitator agent

### ISSUE THREAD

**Issue by schemar** [OpenST/JLP#5]
## Story
As a user
I want to facilitate branded token stake and redeem
Because it should surface errors in branded tokens
And it should provide feedback on how to improve the interaction layers

## Scenario
Given that I run the `bt` binary
When I pass it a sub-command
Then it executes the given sub-command and exits

## Info
The binary would have the following sub-commands:

Command | Explanation
--- | ---
`deploy` | Deploys a new gateway composer
`stake` | Stakes an amount into the branded token
`redeem` | Redeems an amount out of the branded token
`transpose` | Progresses tokens across chains, should be able to re-use most of the functionality of the `facilitate` binary (#3)

* `deploy` should deploy a new instance of the gateway composer and return the addresses to the command line
* `stake` and `redeem` should stake and redeem a given amount
* `transpose` should facilitate the stake/redeem processes

❓Do we need `transpose` as a command here or would that be taken over by the `facilitate` command from #3? How would the transpose command work exactly? (see examples)
❓How to use addresses? Extra addresses per bt? How funded?

Examples:
```
$ bt deploy
$ bt stake 20.00
$ bt redeem 1.5
$ bt transpose stake <?amount?>
$ bt transpose redeem <?amount?>
```

* Using the gateway composer and doing the staking must be done from two different addresses
* All logging must be done to a file (filename `bt_yearmonthdayhourminutesecond_randomstring.log`)
* Use [winston](https://github.com/winstonjs/winston) for logging
* Use [commander](https://github.com/tj/commander.js) like here: https://github.com/OpenSTFoundation/mosaic.js/pull/45

⚠️ Make sure that you align with other CLI tasks on commander and logging structure.
⚠️ Chain access and contract addresses should be read from the config file from #1.

**Comment by schemar** [comment]
Accidentally closed

**Comment by abhayks1** [comment]
The implementation of the ticket consumes proofGenerator of Mosaic.js. 
proofGenerator in mosaic.js uses eth_getProof jsonrpc call. ZeroClientProvider uses web3-provider-engine as ProviderEngine which has implemented sendAsync but throws error on calling send.
```
Error: Web3ProviderEngine does not support synchronous requests.
```

The ticket should be closed after fixing https://github.com/openst/mosaic.js/issues/158

**Comment by schemar** [comment]
JLP is considered "✅ done" for now.
