### ISSUE TITLE
Setup JLP smoke tests to create and fund addresses from mosaic and ropsten faucet.  Also return remaining amount to faucet after test finishes.  

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/JLP#55]

**Comment by benjaminbollen** [comment]
merge conflict; should now be unblocked with the public RPC

**Comment by benjaminbollen** [comment]
I will pick this up and progress it

**Comment by sarvesh-ost** [comment]
Why is pending in this ticket?

**Comment by schemar** [comment]
@pgev please see my comments on PR #53 as well.

**Comment by benjaminbollen** [comment]
@sarvesh-ost please let's prioritise this and resolve

**Comment by schemar** [comment]
JLP is considered "✅ done" for now.
