### ISSUE TITLE
In JLP, opening a connection should support multiple accounts unlock  

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/JLP#57]
https://github.com/OpenST/JLP/blob/b57bc06383014b5f49933a60b669ff82d157a562/src/connection/index.js#L38

There are different actors in JLP smoke tests like deployer, owner, worker etc. Before running tests, these accounts should be unlocked. The current implementation of connection class supports only unlocking of one account per chain.

**Comment by schemar** [comment]
@sarvesh-ost and I had a short call on this.

Basically, the tests should use the `ZeroClientProvider` and provide it with a `signTransaction` function that selects the appropriate function based on the transaction's `from` property.

@sarvesh-ost *maybe* it is feasible to add the support to the main connection/provider and use that in the tests.

**Comment by sarvesh-ost** [comment]
I made some progress on this. It's committed [here](https://github.com/sarvesh-ost/JLP/tree/support_multiple_unlocked_account_for_smoke_test).  

But I am getting the error `(node:9191) UnhandledPromiseRejectionWarning: Error: Provider not set or invalid`. 

Refer: 
https://github.com/sarvesh-ost/JLP/blob/support_multiple_unlocked_account_for_smoke_test/test/hooks.js#L19

**Comment by benjaminbollen** [comment]
we should reconsider whether this ticket is needed now.  First this ticket combines two different issues:
1. having multiple addresses in the web3 provider
2. funding them separately from a faucet;

some remarks:
- we can first use the same address for the different functions, the objective is not to test ACL here (yet; we've done that in the unit tests)
- if we do unlock multiple accounts on the provider, then a single faucet funding event, should be used for the initial funds and then redistributed (per chain)

**Comment by schemar** [comment]
> I made some progress on this. It's committed [here](https://github.com/sarvesh-ost/JLP/tree/support_multiple_unlocked_account_for_smoke_test).
> 
> But I am getting the error `(node:9191) UnhandledPromiseRejectionWarning: Error: Provider not set or invalid`.
> 
> Refer:
> https://github.com/sarvesh-ost/JLP/blob/support_multiple_unlocked_account_for_smoke_test/test/hooks.js#L19

Maybe you are not using the same Web3 object to create the accounts and assign the provider? You have to instantiate a single Web3 instance per account, generate the account with it and add the provider to that very same instance.

> we should reconsider whether this ticket is needed now. First this ticket combines two different issues:
> 
>     1. having multiple addresses in the web3 provider
> 
>     2. funding them separately from a faucet;
> 
> 
> some remarks:
> 
>     * we can first use the same address for the different functions, the objective is not to test ACL here (yet; we've done that in the unit tests)
> 
>     * if we do unlock multiple accounts on the provider, then a single faucet funding event, should be used for the initial funds and then redistributed (per chain)

True 👍 @pgev are you currently working on this?

**Comment by benjaminbollen** [comment]
closing this JLP ticket to refocus attention
