### ISSUE TITLE
Travis should connect to ropsten and 200 chain to run the smoke test

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/JLP#58]
Smoke test should run on ropsten as origin chain and 200 chain as auxiliary chain. Travis build should connect to ropsten and 200 chain to run smoke tests.

**Comment by schemar** [comment]
Travis must access Ben's test nodes via SSH. Find out how to securely add an SSH private key to Travis so that it can connect. Also add the corresponding pub key to Ben's server.

**Comment by benjaminbollen** [comment]
travis for public repos doesnt support (obviously) setting private ssh key to tunnel to the node; will setup an extra public node that is has a public rpc for now

**Comment by schemar** [comment]
@benjaminbollen is this still under review? How can I assist?

**Comment by schemar** [comment]
@benjaminbollen / @sarvesh-ost this ticket is under review but I cannot find the relevant PR. Is this maybe in the wrong column?

**Comment by benjaminbollen** [comment]
this is out-of-date with a local node setup for travis.
