### ISSUE TITLE
Setup of OpenST under test framework

### ISSUE THREAD

**Issue by abhayks1** [OpenST/JLP#67]
There is already executable for setup of openst which deploys below contracts:
- TokenHolder master copy
- Gnosis master copy
- Recovery master copy
- UserWalletFactory contract
- ProxyFactory contract
- CreateAndUserModules

This ticket makes sure openst setup is also there in test framework.

**Comment by abhayks1** [comment]
25/03/2019: Addressed Banks PR changes today

**Comment by benjaminbollen** [comment]
reviewing
