### ISSUE TITLE
Branded Token Stake and Mint should use token holder as a beneficiary instead of external account

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/JLP#75]
Branded token stake and mint smoke test currently mint tokens to an external account. 
Current work for setting up a user wallet is in progress in PR. Refer: #71. 

Once #71 and #73 is merged. This ticket will be ready for development. 

Openst setup smoke test needs Organization and UBT address.
Currently hardcoded values of Organization and UBT is being consumed.
As part of this ticket let's remove the hardcoding and consume Organization and UBT address from chainConfig object.

**Comment by abhayks1** [comment]
openst setup smoke test needs Organization and UBT address. 
Currently hardcoded values of Organization and UBT is being consumed.
As part of this ticket let's remove the hardcoding and consume Organization and UBT address from chainConfig object.

**Comment by abhayks1** [comment]
Closing this ticket as the integration has been taken care in PR #71, Issue #69
