### ISSUE TITLE
Run JLP smoke tests on local geth instances

### ISSUE THREAD

**Issue by pgev** [OpenST/JLP#76]
Currently, JLP tests are assumed to run on "real/live" (1409, "ropsten", etc) geth instances.
The aim of this ticket is to make it possible to run tests on local geth instances (please, see and use two geth-docker-images setup in mosaic-contracts).

**Comment by pgev** [comment]
Implementation branch: https://github.com/pgev/JLP/tree/run-local

**Comment by benjaminbollen** [comment]
reviewing the PR

**Comment by benjaminbollen** [comment]
there was a small comment that can be updated (info level); can be done in a next piece of work
