### ISSUE TITLE
Refactor the code to avoid multiple writing in setupOpenst method

### ISSUE THREAD

**Issue by gulshanvasnani** [OpenST/JLP#92]
As setupOpenst configuration is per economy we must only write the configuration under `utilityBrandedTokens` in chainConfig. Currently we are writing openst data like `tokenHolderMasterCopy`, `gnosisSafeMasterCopy`, `recoveryMasterCopy`, `userWalletFactory` at config level and under utilityBrandedTokens array.

Remove below change :-
https://github.com/OpenST/JLP/blob/master/src/openst.js#L73
Refactor the code accordingly whereever applicable.

**Comment by benjaminbollen** [comment]
improvements to chainConfig need to be done at 
```
mosaic-chains > mosaic
```
OpenST config information shouldnt go into the chainConfig file - if we are to refactor this.

What is it blocking?

**Comment by benjaminbollen** [comment]
moving it to backlog for pick up, but let's keep any refactoring to the absolute minimum; even as-is, with overwriting this data, it's ok.  JLP is only a test framework currently

**Comment by schemar** [comment]
JLP is considered "✅ done" for now.
