### ISSUE TITLE
Verify transfer of BTs using PricerRule for stablecoins

### ISSUE THREAD

**Issue by gulshanvasnani** [OpenST/JLP#97]
This ticket will verify the transfer of BTs using PricerRule's pay when stablecoin like USDC which has 6 decimals is used for staking.

**Comment by jasonklein** [comment]
@gulshanvasnani: can you clarify whether the question concerns the _value token_ or the _utility branded token_ decimals?

Value token decimals have no impact on `PricerRule` logic. The only decimals that concern `PricerRule` transfer logic are:
- utility branded token decimals
- utility branded token conversion rate decimals

**Comment by schemar** [comment]
And please specify how this differs from #96. I don't understand it 😞

**Comment by deepesh-kn** [comment]
The staked coin is not going to impact any logic for pricer rule, as it's in the auxiliary chain.

If the concern here is related to the decimals then it has been tested in the following tickets.

https://github.com/OpenST/brandedtoken-contracts/issues/172
https://github.com/OpenST/brandedtoken-contracts/issues/171
https://github.com/OpenST/openst-contracts/issues/208
https://github.com/OpenST/openst-contracts/issues/204

Closing this ticket.
